trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: 'src'
  displayName: 'Compile ASP.NET Core Web API: $(buildConfiguration)'

- task: AzureCLI@2
  displayName: 'Provision Infrastructure via Terraform'
  env:
    TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
  inputs:
    azureSubscription: 'Azure DevOps Service Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Initializing Terraform..."
      cd infrastructure
      terraform init

      echo "Check Terraform Format..."
      terraform fmt -check

      echo "Planning Terraform deployment..."
      terraform plan -out=tfplan

      echo "Applying Terraform deployment..."
      terraform apply -auto-approve tfplan
